version: "3.8"

services:

  #angular frontend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./angular-frontend
      target: development
    command: npm run start
    volumes: 
      - ./angular-frontend:/suraj/frontend/src/app
      - ./suraj/frontend/src/app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - api          
  
  api:
    build:
      dockerfile: Dockerfile
      context: ./todo-api
      target: development
    volumes: 
      - ./todo-api:/suraj/src/app
      - /suraj/src/app/node_modules/
    # dev mode:npm run start:dev
    command: npm run start:dev
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/db
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 3501:5432

  postgres_admin: 
    image: dpage/pgadmin4:6.12
    depends_on: 
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5051:80
